version: '3'
services:
    web:
      image: hio-api:latest
      restart: always
      ports:
          - 8085:8085
      depends_on:
          - db
    db:
        container_name: sample_db
        image: postgres:9.5
        volumes:
            - sample_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=hio.ro
            - POSTGRES_USER=hio
            - POSTGRES_DB=hio
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
    app:
      image: 'hio-app:latest'
      build: '.'
      ports:
        - 8080:8080

volumes:
    sample_db: {}
