spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hio
    username: hio
    password: hio.ro
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
        show_sql: true
        id:
          new_generator_mappings: false
          
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 36000000
      

admin:
  prefix-url: admin

spring.profiles.include: 'routes'
server:
  port: 8085
