spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hio
    username: postgres
    password: parola123
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
        show_sql: true
        id:
          new_generator_mappings: false
          
security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 36000000
      
UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data


admin:
  prefix-url: admin

spring.profiles.include: 'routes'
server:
  port: 8081
