version: '3'
services:
    web:
      image: hio-back-api:latest
      restart: always
      ports:
          - 8080:8081
      depends_on:
          - db
    db:
        container_name: sample_db
        image: postgres:9.5
        volumes:
            - sample_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=hio.ro
            - POSTGRES_USER=hio
            - POSTGRES_DB=hio
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432

volumes:
    sample_db: {}
